<a href="https://colab.research.google.com/github/vermabhineet84-max/AbhineetVerma-UM-Assignments/blob/main/Numpy_Advanced_Assignment_COMPLETED(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [13]:
#import numpy module with alias np

import numpy as np

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [14]:
# Define a numpy array passing a list with 1, 2 and 3 as elements
arr = np.array([1, 2, 3])

In [15]:
# print output
print(arr)

[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [16]:
# Define a, b, c and d
a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]]])

Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [17]:
# Print dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [18]:
# Print shapes
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(3,)
(2, 3)
(1, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [19]:
# Print data types
print(c.dtype)
print(d.dtype)

int64
int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [20]:
# Print variable types
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [21]:
# Check length of b
len(b)

3

Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [22]:
l1 = [10, 20, 30]
l2 = [40, 50, 60]
l3 = np.array(l1)
l4 = np.array(l2)

Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [23]:
%timeit [x * y for x, y in zip(l1, l2)]

468 ns ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [24]:
%timeit l3 * l4

610 ns ± 9.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [25]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [26]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# Numbers from 1 to 16
x = np.arange(1, 17)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [29]:
x.reshape(2, 8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [30]:
x.reshape(2, 4, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [31]:
x.reshape(4, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
y = x.reshape(2, 4, -1)
print(y)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [33]:
y.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [34]:
a = np.arange(2, 18, 2)
print(a)

[ 2  4  6  8 10 12 14 16]


In [35]:
a[2]

np.int64(6)

In [36]:
print(a[2])
print(a[4])
print(a[6])

6
10
14


Lets check the same for 2 D array

In [37]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [38]:
a[2, 2]

np.int64(9)

Well done!

Now lets check indexing for 3 D array

In [39]:
b = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

In [40]:
b[0, 1, 2]

np.int64(6)

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[0:5]

array([1, 2, 3, 4, 5])

Note: The result includes the start index, but excludes the end index.



In [43]:
arr[5:]

array([6, 7, 8, 9])

In [44]:
arr[:5]

array([1, 2, 3, 4, 5])

**STEP**

Use the step value to determine the step of the slicing:

In [45]:
arr[1:7:2]

array([2, 4, 6])

Did you see? using step you were able to get alternate elements within specified index numbers.

In [46]:
arr[::2]

array([1, 3, 5, 7, 9])

well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [47]:
# Print array a
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
a[2, 1:5]

array([8, 9])

In [49]:
a[:, 2]

array([3, 6, 9])

In [50]:
a[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [51]:
x1 = np.array([1, 2, 3, 4, 5])

In [52]:
x2 = x1

In [53]:
print(x1)
print(x2)

[1 2 3 4 5]
[1 2 3 4 5]


Ok now you have seen that both of them are same

In [54]:
x2[0] = 10

In [55]:
print(x1)
print(x2)

[10  2  3  4  5]
[10  2  3  4  5]


In [56]:
x3 = x1.view()

In [57]:
np.shares_memory(x1, x3)

True

Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [58]:
x3[0] = 100

In [59]:
print(x1)
print(x3)

[100   2   3   4   5]
[100   2   3   4   5]


Now its proved.

Lets see how **Copy()** function works

In [60]:
x4 = x1.copy()

In [61]:
x4[-1] = 900

In [62]:
print(x1)
print(x4)

[100   2   3   4   5]
[100   2   3   4 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [63]:
np.shares_memory(x1, x4)

False

**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [64]:
np.hstack((x1, x4))

array([100,   2,   3,   4,   5, 100,   2,   3,   4, 900])

In [65]:
np.vstack((x1, x4))

array([[100,   2,   3,   4,   5],
       [100,   2,   3,   4, 900]])

We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [66]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Join along rows
np.concatenate((arr1, arr2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [67]:
# Join along columns
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [68]:
np.append(arr1, arr2)

array([1, 2, 3, 4, 5, 6, 7, 8])

Lets use insert() function which Inserts values into array before specified index value

In [69]:
np.insert(x1, 4, x4)

array([100,   2,   3,   4, 100,   2,   3,   4, 900,   5])

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [70]:
np.delete(x2, 1)

array([100,   3,   4,   5])

Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!